### PR TITLE
Add output languages ECMAScript5 and ECMAScript6

### PR DESCRIPTION
**Pull request by prantlf**
Add Handlebars templates with the current features for the new languages.
Generate test files for the new languages.
Work around a problem with using object methods instead of attributes in Handlebars.
Add hasMethods and hasFields methods to Class to be able to omit code blocks entirely.

### CODE REVIEW

**Comment by arwenvaughan** [comment]
Fantastic. I will push out an new version of the code to PlantText.com soon so the service will work with these changes.

**Comment by prantlf** [comment]
Thanks! The language, which plantuml-code-generator is written in, couldn't be missing, could it? :-)

**Comment by arwenvaughan** [comment]
Good point! :)

On Wed, Apr 1, 2015 at 5:32 PM, Ferdinand Prantl <notifications@github.com>
wrote:

> Thanks! The language, which plantuml-code-generator is written in,
> couldn't be missing, could it? :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bafolts/plantuml-code-generator/pull/6#issuecomment-88663469>
> .
>



-- 
Arwen

C: 832-326-9287
H: 303-261-8606
arwenvaughan@gmail.com

**Comment by bafolts** [comment]
When I saw this pull request come through it suddenly was obvious that the most important language was missing from the output!

**Pull request merged**
